### ISSUE TITLE
Screenshots in Lies of P not appearing.

### ISSUE THREAD

**Issue by saikousocial** [rthomasv3/Scum-Bag#10]
It's not specific to Lies of P, but it's the game I am currently playing.

Any idea if I've done something wrong? Here are the logs.

[logs.txt](https://github.com/user-attachments/files/23707525/logs.txt)

**Comment by rthomasv3** [comment]
Hi, thanks for reporting this issue. I'll take a look at it after work today and see what I can do.

**Comment by rthomasv3** [comment]
I don't have Lies of P to test things out, but looking through the code and logs, I have a guess at the issue.

It looks like Lies of P has more than one process running, and the code is picking the wrong process to try to take a screenshot of.

This line from the logs is the key:
```
WindowHandle is required when Target is Window
```

I pushed up an attempted fix to better detect the correct game process. Check out [Release v1.2.1](https://github.com/rthomasv3/ScumBag/releases/tag/v1.2.1) and let me know if it's working for you now.

If not, I'm happy to take another look.

**Comment by saikousocial** [comment]
That solved it!

I even loaded the game up through Special K, and it still worked.

The logs still show the error of being unable to find the game process, but it's all working as intended, as far as I can tell.

[logs.txt](https://github.com/user-attachments/files/23758572/logs.txt)

Lies of P _does_ have two executables, **LOP.exe** and **LOP-Win64-Shipping.exe**, so perhaps that could be the reason why it couldn't be detected before?

In any case, you fixed it! Thank you!

**Comment by rthomasv3** [comment]
Awesome, glad it worked.

It looks like there are some changes that happen to the save file before the main window is fully open, so that's why the logs show the initial failures. But then after the game fully launches it finds the process and everything starts working. So yeah, you can just ignore those errors.

Thanks again for letting me know about the issue. Let me know if you run into any other problems.
